### ISSUE TITLE
Crash due to dependency on implementation defined code

### ISSUE THREAD

**Issue by Siphalor** [LolHens/dynmap-fabric#18]
Your code seems to depend on `ZipFileSystem`. This class is implementation specific code of Sun's java implementation (you can see that because it's in the `com.sun` package). You should never depend on implementation node since that is not guaranteed to run with every JRE.

On my server I'm running OpenJDK 11:
```
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Debian-1, mixed mode, sharing)
```

This is an example crash log:
https://paste.siphalor.de/?dfa7a5dbba343b11#A6JScRGPHjGXsfo9vrRm9pg6msJRhgMrFh1crX5KsQsJ

**Comment by lhns** [comment]
Good catch! fixed in 0.2.9
