### ISSUE TITLE
Corruption when rendering world.

### ISSUE THREAD

**Issue by LarveyOfficial** [LolHens/dynmap-fabric#20]
https://map.gustapotown.xyz/?worldname=world&mapname=flat&zoom=6&x=-883&y=64&z=532
You can see here, I stopped rendering as my log was flooded with
``[16:57:08] [Dynmap Render Thread/WARN]: [Dynmap] Got statelist of length 320 but expected a length of 342``
Hopefully this can be fixed soon as right now this makes the mod un usable :(

**Comment by lhns** [comment]
Duplicate of #19
