### ISSUE TITLE
The end and Nether maps are swapped in new installation of the Mod.

### ISSUE THREAD

**Issue by LarveyOfficial** [LolHens/dynmap-fabric#21]
https://map.gustapotown.xyz
as you can see here, when going to the_end world it shows a red background indicating its the nether, and shows no chunks as no one has gone there, but when going to the_nether it shows a black background and is showing the nether roof on the map, seems that the maps are flip flopped.
the_nether
![image](https://user-images.githubusercontent.com/39219859/90277052-e4686780-de32-11ea-8397-b5aa187f44c9.png)
the_end
![image](https://user-images.githubusercontent.com/39219859/90277068-eb8f7580-de32-11ea-8f75-fc3de887603c.png)

**Comment by lhns** [comment]
fixed by c93091b0fa17c81a47eec37c1221a2d609670140 and 7b1bf073aaf11d23404099db5737854ca0af7a71 in 0.2.10
you will probably have to delete dynmap/fabricworlds.yml and let it regenerate
