### ISSUE TITLE
Triggering a fullrender in for The End dimension (DIM1) will result in 0 tiles rendered

### ISSUE THREAD

**Issue by bleuthoot-sven** [LolHens/dynmap-fabric#34]
When using `/dynmap fullrender DIM1` will result in 0 tiles being rendered, even though the end has already been generated or if I am in The End dimension itself. Using `radiusrender` will work.

The Overworld and the Nether Dimension work fine.

![](https://i.imgur.com/PNrZ1NA.png)

### Version

Minecraft Version: 1.16.2
Fabric build: 0.9.1+build.205

### Installed server mods

- dynmap-fabric-0.2.15+1.16.2
- fabric-api-0.17.2+build.396-1.16
- fabric-carpet-1.16.2-1.4.8+v200811
- lithium-fabric-mc1.16.2-0.5.1-SNAPSHOT (Unreleased build taken from building [The lithium repo](https://github.com/jellysquid3/lithium-fabric))
- phosphor-fabric-mc1.16.2-0.6.0-SNAPSHOT (Unofficial build taken from building [This fork of phosphor](https://github.com/mrgrim/phosphor-fabric/tree/1.16.2-dev))

**Comment by lhns** [comment]
Very interesting that radiusrender works but fullrender doesn't.

**Comment by bleuthoot-sven** [comment]
Not sure what happened, since I haven't updated anything. The rendering in The End works again. I am not sure why.

I will close this issue. If it for some reason comes back, I'll create a new issue and I hope I'll get more information out of it.

**Comment by lhns** [comment]
I have seen similar reports on the official dynmap discord so this might also be a problem in the official version.
