### ISSUE TITLE
Dynmap commands don't seem to exist

### ISSUE THREAD

**Issue by EnKrypt** [LolHens/dynmap-fabric#35]
![dynmap](https://user-images.githubusercontent.com/1106939/90989574-65a0c680-e5b8-11ea-9a15-7cf75b7f703b.jpg)

Tried on server console, as well as in game chat (as operator). It's almost as though no such commands exist. Typing `/dynmap fullrender` does nothing.

Mod version: dynmap-fabric-0.2.16+1.16.1.jar
Minecraft server: 1.16.1
Other mods:
![mods](https://user-images.githubusercontent.com/1106939/90989621-d7791000-e5b8-11ea-8a5f-be7f37ef19a2.jpg)

**Comment by EnKrypt** [comment]
Extra note: The dynmap web UI itself works great, it's just the commands that I can't seem to access.

**Comment by lhns** [comment]
This is an incompatibility problem with worldedit at the moment.

**Comment by i509VCB** [comment]
The solution is to use `CommandRegistrationCallback` so worldedit force reloading commands due to platform setup doesn't drop your commands you add at server start

**Comment by lhns** [comment]
Thanks to @i509VCB this is now fixed in 0.2.17
